FROM oven/bun:1 AS dev

ENV NODE_ENV=development

WORKDIR /app

COPY package.json bun.lock ./

RUN bun install

COPY . .

RUN chown -R bun:bun /app

USER bun

EXPOSE 5173

CMD ["bun", "run", "dev", "--", "--host"]
